workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    environment:
      java: 17
    scripts:
      - name: Show Gradle version
        script: |
          cat gradle/wrapper/gradle-wrapper.properties
      - name: Build debug APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
