workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    environment:
      android:
        apiLevel: 34
      groups:
        - gradle
    cache:
      cache_paths:
        - ~/.gradle/caches
    scripts:
      - name: Set local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - notifications@example.com
