workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    scripts:
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk